# ██╗   ██╗ █████╗ ███████╗██╗
# ╚██╗ ██╔╝██╔══██╗╚══███╔╝██║
#  ╚████╔╝ ███████║  ███╔╝ ██║
#   ╚██╔╝  ██╔══██║ ███╔╝  ██║
#    ██║   ██║  ██║███████╗██║
#    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝
#
# Yazi Config File by Arfan Zubi

[flavor]
use = "catppuccin-mocha"

# For upcoming Yazi 0.4 (nightly version):
dark = "catppuccin-mocha"
